[server]
port = 5558

[node]
detect_drivers = false
# override-max-sessions = true
# max-sessions = 15

[relay]
url = "http://localhost:4726/wd/hub"
status-endpoint = "/status"
configs = [
	"1", '{"browserName": "safari", "platformName": "iOS","deviceName": "iPhone 12 PRO MAX", "appium:platformVersion": "15.5"}'
]
